sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: JYhybiSVu+VACRFiGwg0niIWd3ZSqo5NN1I1irws5EW+hyD4tGyIRijsFYDtyDIsashO2PWPZ0qAvkkvlf0zZ4++GnvqDe5wkPJ6s5VxbJXjva9OLLbGttRkJlEH1pae414JcWcDLg2b/20Ez5veEreds3G923Q8GZMoQ7LYdNifWv0cFBH9Og0hjJV6rQM193A076V2iEwhZiVKrIpB3ztG0NApyrKGJxtVOGiag1V1jdJ2E5FfuM2iWJCs1aymRXtva6ctwxlAsgvhUl1bLWQnECTUiLEyMlqkYijYO5BQmZFQjxwm+ud2XrXlzhSYhV1OaGJBkQp+eD58rXEEY3Ye4Laftxm08ePi3FvLPYh83v3BfOBjq74X2qodzUZ/UAJ0RK7DnCCcRYmUW2WluqQ61CVOSB80rkauwihbEvAkX5obme4WyniYdL9Oz8DFW0ETGPPA+rqrI54he/TsussPmjmUHA6BydPqjNa/zPLZTVUC/n+CQ08vPTV+P4G010ugLMQY46rCtvSHpdrJQDLm2MQVvIyLmTa6cbc0mlYNoqxGVmNvo1yQ6EQMx97IhPVitJl9zjdA20lRn4RMQg9ahr93Vldr3VZYLPRfM2MpD6L11u5T04ndb72ihYHE8b2C3DPx7NgXShfHsNDNOJ/fnMdd8EKUG08SopZu0pw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/History-of-the-Decline-and-Fall-of-the-Roman-Empire---Volume-6_736
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy